### ISSUE TITLE
On selection callback?

### ISSUE THREAD

**Issue by brennanbatalla** [uptick/react-keyed-file-browser#115]
I am not sure if this exists, but I was looking through the code and was unable to find a callback when you click on a file or folder that returns the file object.

**Comment by klm-lab** [comment]
HI @brennanbatalla 

`<FileBrowser
    onSelectFile={this.handleSelectFile}
    onSelectFolder={this.handleSelectFolder}
/>`

**Comment by vinicvaz** [comment]
Hello.
onSelectFile is working fine but onSelectFolder event is returning undefined, any sugestions please?
Thanks

**Comment by harsh-tamr** [comment]
Duplicates: https://github.com/uptick/react-keyed-file-browser/issues/143

**Comment by harsh-tamr** [comment]
Ok looking at the code I've discovered how the onSelect callback works.
If you files look like
`/a/b/c.txt, /a/b/d.txt`, then you will get undefined for the folder calls because no folders have been defined.

If you have `/a/, a/b/, /a/b/c.txt, /a/b/d.txt` then you will not get undefined but the folder you are looking for.

The problem lies in https://github.com/uptick/react-keyed-file-browser/blob/master/src/browser.js#L178
where .find is looking for an exact match. 

I would argue that a user should not have to specify all the folders and if a prefix exists, return a select with a folder and no modified, size. I'll create a PR to do just this.

**Comment by harsh-tamr** [comment]
also solved by https://github.com/uptick/react-keyed-file-browser/pull/149
