### ISSUE TITLE
'define' is not defined Error while using the 'FileBrowser' component after building ('dist/react-keyed-file-browser.js')

### ISSUE THREAD

**Issue by girijant** [uptick/react-keyed-file-browser#58]
**Step-1:** After executing 'npm run prepublish', build is got successful, both 'react-keyed-file-browser.js' and 'react-keyed-file-browser.css' files are observed from the 'dist' directory.
**Step-2:** Imported and used the 'FileBrowser' component from the above 'dist/react-keyed-file-browser.js', Seeing below compilation error by 'npm start':
```
Failed to compile.
./src/file-browser/react-keyed-file-browser.js
  Line 4:  'define' is not defined  no-undef
  Line 5:  'define' is not defined  no-undef
```
**Step-3:** Installed 'react-keyed-file-browser' package separately by 'npm install react-keyed-file-browser' to compare both 'react-keyed-file-browser.js' files.
**Step-4:** Seeing many difference by comparing my 'react-keyed-file-browser.js' (dist/react-keyed-file-browser.js) content with the '<project>\node_modules\react-keyed-file-browser\dist\react-keyed-file-browser.js'

Please find below attachment of both files for your reference.

[react-keyed-file-browserJS_nodeModule.txt](https://github.com/uptick/react-keyed-file-browser/files/2995771/react-keyed-file-browserJS_nodeModule.txt)
[react-keyed-file-browserJS_myDist.txt](https://github.com/uptick/react-keyed-file-browser/files/2995772/react-keyed-file-browserJS_myDist.txt)

Many Thanks,
~Girija

**Comment by jlo-1** [comment]
Hi @girijant, are you able to show me your FileBrowser import statement where you are trying to import the component.

Cheers

**Comment by girijant** [comment]
Hi @jlo-1, Here are the steps, how I used the 'react-keyed-file-browser.js' in my project
**Step-1:** Created a sample project 'Test-Demo' inside the 'react-keyed-file-browser-master' project.
**Step-2:** After building the 'react-keyed-file-browser-master', copied both 'react-keyed-file-browser.js' and 'react-keyed-file-browser.css' files from the 'dist' to my project dir 'Test-Demo/file-browser'.
**Step-3:** Created a 'FileViewDemo' component and imported 'FileBrowser' component from the above dir 'file-browser/react-keyed-file-browser' by:
`import FileBrowser from './file-browser/react-keyed-file-browser';`

**Detail code of my 'FileViewDemo':**
```
import React, { Component } from 'react';
import Moment from 'moment';
//import FileBrowser from 'react-keyed-file-browser';
import FileBrowser from './file-browser/react-keyed-file-browser';

//My component
class FileViewDemo extends Component {
    render() {
        return (
            <div>
              <FileBrowser
                files={[
                  {
                    key: 'cat.png',
                    modified: +Moment().subtract(1, 'hours'),
                    size: 1.5 * 1024 * 1024,
                  },
                  {
                    key: 'kitten.png',
                    modified: +Moment().subtract(3, 'days'),
                    size: 545 * 1024,
                  },
                  {
                    key: 'elephant.png',
                    modified: +Moment().subtract(3, 'days'),
                    size: 52 * 1024,
                  },
                ]}
              />
           </div>
        );
}
}
export default FileViewDemo;
```
 I also installed 'react-keyed-file-browser' package for the same project (i.e. 'Test-Dempo') by 'npm install react-keyed-file-browser' and imported the 'FileBrowser' component from node-module (i.e. import FileBrowser from 'react-keyed-file-browser) in the above 'FileViewDemo' class, 'FileBrowser' compoent is succefully loaded and viewed in the browser by 'npm start' withour any error. But 'import FileBrowser from './file-browser/react-keyed-file-browser';' didn't work

Attaching snapshot of my VSCode IDE for your reference:

![FileViewDemo](https://user-images.githubusercontent.com/17194046/54868007-b56cd400-4dad-11e9-8d3c-00fb6e538ded.png)
.

**Comment by girijant** [comment]
@jlo-1, 
Please let me know if you need any additional info. 

Many Thanks,
~Girija

**Comment by girijant** [comment]
@jlo-1 , @scaredcat,
Is anything wrong in my project setup or any update on this ticket ?

**Comment by scaredcat** [comment]
Hi @girijant 

I'm assuming the reason you're building `react-keyed-file-browser` yourself instead of importing it from the npm package provided is that you'd like to make some changes to our code to suit your particular project. If that is the case, the part that is going wrong is where you copy the build output into your `Test-Demo` project and it is trying to transpile the code a second time, throwing the error.

What I'd recommend is to make use of `npm link` or `yarn link` to set up your development environment. Below is how I have done it using `npm link`:

Have both your project and `react-keyed-file-browser` in a working directory such as:
```
.
├── react-keyed-file-browser
│   ├── babel.config.js
│   ├── demo-site
│   ├── dist
│   ├── index.js
│   ├── jsconfig.json
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   ├── README.md
│   ├── src
│   ├── stories
│   ├── webpack.config.js
│   └── yarn.lock
└── Test-Demo
    ├── node_modules
    ├── package.json
    ├── package-lock.json
    ├── public
    ├── README.md
    └── src
```
Notice that I've already built `react-keyed-file-browser` as a `dist` folder is present in that directory

Then following steps from `npm-link` https://docs.npmjs.com/cli/link.html In my case I needed to install node again using node version manager because of permissions, but otherwise the following should work

```bash
cd react-keyed-file-browser
npm link
cd ../Test-Demo
npm link react-keyed-file-borwser
```

You would know if you've done it correctly when
```bash
./TestDemo $ ls -l node_modules/react-keyed-file-browser
lrwxrwxrwx 1 scaredcat scaredcat 81 Mar 30 11:47 react-keyed-file-browser -> ../../../../.nvm/versions/node/v11.13.0/lib/node_modules/react-keyed-file-browser
```

Notice the presence of `->` which is the symbolic link that `npm link` created between the two projects.

Now whenever you `import FileBrowser from 'react-keyed-file-browser` it will import the one you've built on your local machine rather than the version that is available from npm.

In case you wanted to remove the linking you can simply delete your `node_modules` and `npm install` again.

 Please let me know if any of the steps described above does not work for you and I'll try my best to help.

Retief

**Comment by girijant** [comment]
@scaredcat , 
The intention of building 'react-keyed-file-browser' is to modify some source components as per my project need. Thanks and appreciating your analysis for this issue . But main root cause of my issue is below :

 **After executing 'npm run prepublish', build is got successful, both 'react-keyed-file-browser.js' and 'react-keyed-file-browser.css' files are observed from the 'dist' directory of the project.
But seeing many difference by comparing my 'react-keyed-file-browser.js' (dist/react-keyed-file-browser.js) content with the original '<project>\node_modules\react-keyed-file-browser\dist\react-keyed-file-browser.js'. Which causing the below compilation error by 'npm start':**
```
Failed to compile.
./src/file-browser/react-keyed-file-browser.js
  Line 4:  'define' is not defined  no-undef
  Line 5:  'define' is not defined  no-undef
```
**Please find below attachment of both files for your reference:**
[react-keyed-file-browserJS_nodeModule.txt](https://github.com/uptick/react-keyed-file-browser/files/2995771/react-keyed-file-browserJS_nodeModule.txt)
[react-keyed-file-browserJS_myDist.txt](https://github.com/uptick/react-keyed-file-browser/files/2995772/react-keyed-file-browserJS_myDist.txt)
 
@jlo-1 ,
Any update for this issue ? 
Any root-cause for such a file difference issue after building the project in my windows environment ?
Currently my project activities are blocked for this issue. Let me know  if you need any support from my side.

Many Thanks,
~Girija

**Comment by scaredcat** [comment]
Hi @girijant 

A simple solution to your problem would be to copy your `react-keyed-file-browser` build and replace the one currently in `node_modules` such as
```bash
Test-Demo$ cp src/file-browser/* node_modules/react-keyed-file-browser/dist/
```
If you don't have bash installed, simply open explorer and manually replace the files. Afterwards use
```javascript
import FileBrowser from 'react-keyed-file-browser'
```
to import your build.

Since you've replaced the one in `node_modules` with your own, this will now be importing your version.

The root cause is not your windows environment, but simply where the build output is imported from.

Please let me know whether this solution works for you.

**Comment by scaredcat** [comment]
Closing this issue since haven't heard anything back. Can reopen if still need help.
